### ISSUE TITLE
`mismatched types` error on compile

### ISSUE THREAD

**Issue by Zerowalker** [ArrowMaxGithub/vjoy#1]
```
stable-x86_64-pc-windows-msvc (default)
rustc 1.82.0 (f6e511eec 2024-10-15)
```

```
   Compiling vjoy v0.6.0
error[E0308]: mismatched types
   --> ...\vjoy-0.6.0\src\vjoy.rs:433:32
    |
432 |                 Err(Error::Ffi(FFIError::DeviceCouldNotBeAcquired(
    |                                ---------------------------------- arguments to this enum variant are incorrect
433 |                     device_id, result,
    |                                ^^^^^^ expected `u32`, found `i32`
    |
note: tuple variant defined here
   --> ...\vjoy-0.6.0\src\error.rs:42:5
    |
42  |     DeviceCouldNotBeAcquired(u32, VjdStat),
    |     ^^^^^^^^^^^^^^^^^^^^^^^^
help: you can convert an `i32` to a `u32` and panic if the converted value doesn't fit
    |
433 |                     device_id, result.try_into().unwrap(),
    |                                      ++++++++++++++++++++

```

**Comment by ArrowMaxGithub** [comment]
Can't reproduce on a clean project, neither on the 0.6.0 version from crates.io nor the master branch.

Happy to help figure out this issue, but I'd need more info. 
Since you opened the FFI issue https://github.com/ArrowMaxGithub/vjoy-sys/issues/3# as well and `VjdStat` is a type alias for `c_int`, I suspect there is something unusual about your build environment. 

Otherwise, `c_int` would be an alias for `i32`.

**Comment by Zerowalker** [comment]
hmm, I tried making a new project and just added vjoy.

```
[package]
name = "abc"
version = "0.1.0"
edition = "2021"

[dependencies]
vjoy = "0.6.0"
```

Same issue.

rustup shows this:

```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\...\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc (default)
stable-x86_64-unknown-linux-gnu
nightly-x86_64-pc-windows-msvc
esp

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.82.0 (f6e511eec 2024-10-15)
```

Not sure what can be affecting it. It looks normal to me.

EDIT:

In order to even get to the u32/i32 issue, I need to specify 
`BINDGEN_EXTRA_CLANG_ARGS = "-fdeclspec"`
Else the compilation fails as `__declspec` is not supported without it.

**Comment by ArrowMaxGithub** [comment]
In this case, something about your Clang installation or env-vars used by Clang could be the culprit.

I setup a clean project, installed the vJoy driver, installed Clang via the winget method from LLVM as per https://rust-lang.github.io/rust-bindgen/requirements.html and it worked out of the box. All on a new Win11 machine.

Maybe one of the following extensions is disabled on your machine via an env-var:

https://clang.llvm.org/docs/UsersManual.html#microsoft-extensions

**Comment by Zerowalker** [comment]
Clang was indeed the problem, so this was solved along with the other issue:)

Many thanks, and sorry for the 2 issues that weren't even related to the crates in the end.
