### ISSUE TITLE
[Suggestion] Make Button ID accessible

### ISSUE THREAD

**Issue by Zerowalker** [ArrowMaxGithub/vjoy#2]
Make the `id` of a button accessible.
And perhaps have a `Device::get_button(u8) -> Option<Button>` function as well.
As far as I can tell there is currently no way to access it.
as the `id` points to a specific button (say `X`) it can be used to verify that the buttons exist in the device beforehand.
Without having to use `Device::set_button` to try and see if it fails.

Perhaps there is a way that I missed for this, but if not then just throwing the suggestion out there:)

EDIT: 

Hmm I might have misunderstood how Vjoy works and it just has an X amount of buttons,
so only the amount actually matters.
If so it might be the Axes, but one can get those by iterating and checking the `display_name`,
but getting by Id might be good as well.

So getting axes and button by Id might be a good thing so the suggestion stands,
even though it wasn't as needed probably as I thought.

**Comment by ArrowMaxGithub** [comment]
Adding these getters would be trivial, but I haven't found a good reason for them, personally.

In my projects so far, I have only ever used vJoy on the output side as an "input sink", without reading from it in any way, besides getting the count of the available buttons/axes/hats.

You could however access the button/axis/hat via the iterator getters and get the nth element, returning None if it's out of bounds.
E.g. `vjoy.buttons().nth(5)`

The ID is indeed just a 1-based index into the underlying available buttons/axes/hats.
I choose to follow the 1-based index from vJoy, to avoid confusion, but I'm not the greatest fan.

If you just need the count of the available buttons/axes/hats for a specific device, see `device.num_{buttons,axis,hat}(id)`.

**Comment by Zerowalker** [comment]
There is probably a good reason in the end, just my approach were based on it.
And I ended up not being able to assume all buttons etc existed anyhow so have to recreate them to ensure it.

So my suggestion was not as good as I thought:P
